[package]
name = "aw_guessing"
version = "0.0.1"

[dependencies]
examples = { git = "https://github.com/ENJOY-LAB/AbyssWorld.git", subdir = "./examples", rev = "main" }

[addresses]
aw_guessing =  "0x0"
sui =  "0000000000000000000000000000000000000000000000000000000000000002"
